### ISSUE TITLE
I think the author pre-trained the model using 64 meta-training set + 16 meta-testing set, that's the reason of high performance.

### ISSUE THREAD

**Issue by huangxilang901** [Clarifai/few-shot-ctm#13] opened 2021-07-01 02:42 UTC
Until now, the author still has not provided the pre-training codes of the model. A reasonable guess is that he used 80 classes (64 + 16) to pre-trained the model. So, the proposed method may not actually improve performance, just a work of pre-trained the model on meta-training and meta-testing set.

**Comment by deigen** [comment] 2021-08-10 21:32
Duplicate of https://github.com/Clarifai/few-shot-ctm/issues/11

**Closed** 2021-08-10 21:32 UTC
